import { randomUUID } from 'node:crypto';
import { openDatabase, type DatabaseConnection } from '@beloveddev/database/client';
import { migrateDatabase } from '@beloveddev/database/migrate';

export async function createTestDatabase(
  administratorUrl: string,
  options: { beforeMigrate?: (connection: DatabaseConnection) => Promise<void> } = {},
) {
  const suffix = randomUUID().replaceAll('-', '');
  const databaseName = `beloveddev_test_${suffix}`;
  const roleName = `${databaseName}_runtime`;
  const password = randomUUID().replaceAll('-', '');
  let idleFailure = false;
  let closing = false;
  const onIdleError = () => {
    if (!closing) idleFailure = true;
  };
  const control = openDatabase(administratorUrl, { onIdleError, maxConnections: 1 });
  let admin: DatabaseConnection | undefined;
  let runtime: DatabaseConnection | undefined;
  let databaseCreated = false;
  let roleCreated = false;

  async function close() {
    closing = true;
    try {
      await runtime?.close();
      await admin?.close();
      // Only names generated by this helper can be removed. Never drop a supplied database.
      if (!/^beloveddev_test_[0-9a-f]{32}$/.test(databaseName)) {
        throw new Error('Refusing to clean an unrecognized test database.');
      }
      if (databaseCreated) await control.pool.query(`DROP DATABASE "${databaseName}" WITH (FORCE)`);
      if (roleCreated) await control.pool.query(`DROP ROLE "${roleName}"`);
    } finally {
      await control.close();
    }
    if (idleFailure) throw new Error('An idle test database connection failed.');
  }

  try {
    // Identifiers and password below are generated hexadecimal values, never caller input.
    await control.pool.query(`CREATE DATABASE "${databaseName}"`);
    databaseCreated = true;
    await control.pool.query(
      `CREATE ROLE "${roleName}" LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT`,
    );
    roleCreated = true;
    const url = new URL(administratorUrl);
    url.pathname = `/${databaseName}`;
    admin = openDatabase(url.href, { onIdleError });
    const identity = await admin.pool.query<{ name: string }>('SELECT current_database() AS name');
    if (identity.rows[0]?.name !== databaseName) {
      throw new Error('Refusing to migrate an unexpected test database.');
    }
    await options.beforeMigrate?.(admin);
    await migrateDatabase(admin.db);
    await admin.pool.query(`REVOKE CREATE ON SCHEMA public FROM PUBLIC`);
    await admin.pool.query(`GRANT USAGE ON SCHEMA public TO "${roleName}"`);
    await admin.pool.query(
      `GRANT SELECT ON tenant_memberships, developer_profiles, clients, projects, project_evidence, project_blockers, project_notes TO "${roleName}"`,
    );
    await admin.pool.query(`GRANT SELECT (id, status) ON tenants, users TO "${roleName}"`);
    await admin.pool.query(`GRANT INSERT ON projects TO "${roleName}"`);
    url.username = roleName;
    url.password = password;
    url.searchParams.delete('user');
    url.searchParams.delete('password');
    runtime = openDatabase(url.href, { onIdleError });
    return { admin, runtime, runtimeUrl: url.href, close };
  } catch (error: unknown) {
    await close();
    throw error;
  }
}

export type TestDatabase = Awaited<ReturnType<typeof createTestDatabase>>;
